name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Install Other Tools
      run: sudo apt-get -y install build-essential verilator
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test